import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

class HomeTab extends StatelessWidget {
  const HomeTab({super.key});

  @override
  Widget build(BuildContext context) {
    // Featured prompts for horizontal carousel
    final featuredPrompts = [
      {
        'title': 'DOORS OF KNOWLEDGE',
        'desc': 'Enter the portal of wisdom and design structured prompt pipelines.',
        'category': 'Trending',
      },
      {
        'title': 'DEEP SLEEP PILL',
        'desc': 'Unwind with calming ambient relaxation scripts generated by AI.',
        'category': 'Nature',
      },
      {
        'title': 'INSIDE NATURE',
        'desc': 'Breathe fresh air and explore biological prompts for botanical research.',
        'category': 'Life',
      },
    ];

    // Grid prompts for 2-column list
    final gridPromptsLeft = [
      {
        'title': 'Creative Copywriter',
        'desc': 'Write product descriptions utilizing the AIDA framework.',
        'category': 'Marketing',
        'saves': '943',
      },
      {
        'title': 'SQL Query Optimizer',
        'desc': 'Analyze index paths and join structures in database engines.',
        'category': 'Coding',
        'saves': '1.8k',
      },
    ];

    final gridPromptsRight = [
      {
        'title': 'Socratic AI Tutor',
        'desc': 'Prompts that stimulate critical thinking via interactive Q&A.',
        'category': 'Learning',
        'saves': '2.1k',
      },
      {
        'title': 'Resume Enhancer',
        'desc': 'Rewrite resume bullet points emphasizing action verbs.',
        'category': 'Career',
        'saves': '1.2k',
      },
    ];

    return SingleChildScrollView(
      physics: const BouncingScrollPhysics(),
      child: Padding(
        padding: const EdgeInsets.symmetric(horizontal: 16.0, vertical: 8.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            // 1. Horizontal scrollable list of chips
            SizedBox(
              height: 48,
              child: ListView(
                scrollDirection: Axis.horizontal,
                physics: const BouncingScrollPhysics(),
                children: [
                  _buildCategoryChip(context, 'Trending', true),
                  _buildCategoryChip(context, 'Love', false),
                  _buildCategoryChip(context, 'Girls', false),
                  _buildCategoryChip(context, 'Boys', false),
                  _buildCategoryChip(context, 'Couple', false),
                ],
              ),
            ),
            const SizedBox(height: 16),

            // 2. Horizontal Carousel (Highlighted Prompts)
            SizedBox(
              height: 200,
              child: ListView.builder(
                scrollDirection: Axis.horizontal,
                physics: const BouncingScrollPhysics(),
                itemCount: featuredPrompts.length,
                itemBuilder: (context, index) {
                  final item = featuredPrompts[index];
                  return _buildCarouselCard(
                    context,
                    title: item['title']!,
                    desc: item['desc']!,
                    category: item['category']!,
                  );
                },
              ),
            ),
            const SizedBox(height: 20),

            // Section Title
            Text(
              'All Prompts',
              style: Theme.of(context).textTheme.titleMedium?.copyWith(
                    fontWeight: FontWeight.bold,
                  ),
            ),
            const SizedBox(height: 12),

            // 3. Two-Column Masonry Grid
            Row(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                // Left Column
                Expanded(
                  child: Column(
                    children: gridPromptsLeft.map((item) {
                      return _buildGridCard(
                        context,
                        title: item['title']!,
                        desc: item['desc']!,
                        category: item['category']!,
                        saves: item['saves']!,
                      );
                    }).toList(),
                  ),
                ),
                const SizedBox(width: 12),
                // Right Column
                Expanded(
                  child: Column(
                    children: gridPromptsRight.map((item) {
                      return _buildGridCard(
                        context,
                        title: item['title']!,
                        desc: item['desc']!,
                        category: item['category']!,
                        saves: item['saves']!,
                      );
                    }).toList(),
                  ),
                ),
              ],
            ),
            const SizedBox(height: 24),
          ],
        ),
      ),
    );
  }

  Widget _buildCategoryChip(BuildContext context, String label, bool isActive) {
    final isDark = Theme.of(context).brightness == Brightness.dark;
    final primaryColor = Theme.of(context).primaryColor;
    return Container(
      margin: const EdgeInsets.only(right: 8),
      alignment: Alignment.center,
      child: ChoiceChip(
        label: Text(label),
        selected: isActive,
        selectedColor: primaryColor,
        labelStyle: TextStyle(
          color: isActive 
              ? Colors.white 
              : (isDark ? Colors.grey[300] : Colors.grey[700]),
          fontWeight: isActive ? FontWeight.bold : FontWeight.normal,
        ),
        backgroundColor: isDark ? const Color(0xFF1F1F1F) : Colors.grey[200],
        onSelected: (val) {},
      ),
    );
  }

  Widget _buildCarouselCard(
    BuildContext context, {
    required String title,
    required String desc,
    required String category,
  }) {
    final isDark = Theme.of(context).brightness == Brightness.dark;
    final primaryColor = Theme.of(context).primaryColor;

    return Container(
      width: 140,
      margin: const EdgeInsets.only(right: 12),
      decoration: BoxDecoration(
        gradient: LinearGradient(
          colors: isDark 
              ? [const Color(0xFF2E2E3A), const Color(0xFF1F1F1F)] 
              : [Colors.grey[200]!, Colors.white],
          begin: Alignment.topCenter,
          end: Alignment.bottomCenter,
        ),
        borderRadius: BorderRadius.circular(16),
        border: Border.all(
          color: isDark ? Colors.grey[800]! : Colors.grey[300]!,
          width: 1,
        ),
      ),
      child: Padding(
        padding: const EdgeInsets.all(12.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Container(
              padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 3),
              decoration: BoxDecoration(
                color: primaryColor.withValues(alpha: 0.1),
                borderRadius: BorderRadius.circular(6),
              ),
              child: Text(
                category,
                style: TextStyle(
                  color: primaryColor,
                  fontSize: 9,
                  fontWeight: FontWeight.bold,
                ),
              ),
            ),
            const Spacer(),
            Text(
              title,
              maxLines: 2,
              overflow: TextOverflow.ellipsis,
              style: const TextStyle(
                fontSize: 13,
                fontWeight: FontWeight.bold,
                letterSpacing: 0.2,
              ),
            ),
            const SizedBox(height: 6),
            Text(
              desc,
              maxLines: 3,
              overflow: TextOverflow.ellipsis,
              style: TextStyle(
                fontSize: 10,
                color: isDark ? Colors.grey[400] : Colors.grey[600],
                height: 1.3,
              ),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildGridCard(
    BuildContext context, {
    required String title,
    required String desc,
    required String category,
    required String saves,
  }) {
    final isDark = Theme.of(context).brightness == Brightness.dark;
    final primaryColor = Theme.of(context).primaryColor;

    return Container(
      margin: const EdgeInsets.only(bottom: 12),
      width: double.infinity,
      decoration: BoxDecoration(
        color: isDark ? const Color(0xFF1F1F1F) : Colors.white,
        borderRadius: BorderRadius.circular(16),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withValues(alpha: 0.03),
            blurRadius: 6,
            offset: const Offset(0, 3),
          ),
        ],
        border: Border.all(
          color: isDark ? Colors.grey[850]! : Colors.grey[200]!,
          width: 1,
        ),
      ),
      child: Padding(
        padding: const EdgeInsets.all(14.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                Container(
                  padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 3),
                  decoration: BoxDecoration(
                    color: primaryColor.withValues(alpha: 0.08),
                    borderRadius: BorderRadius.circular(6),
                  ),
                  child: Text(
                    category,
                    style: TextStyle(
                      color: primaryColor,
                      fontSize: 9,
                      fontWeight: FontWeight.bold,
                    ),
                  ),
                ),
                IconButton(
                  icon: const Icon(Icons.favorite_border),
                  color: Colors.grey,
                  iconSize: 18,
                  padding: EdgeInsets.zero,
                  constraints: const BoxConstraints(),
                  onPressed: () {},
                ),
              ],
            ),
            const SizedBox(height: 12),
            Text(
              title,
              style: const TextStyle(
                fontSize: 14,
                fontWeight: FontWeight.bold,
              ),
            ),
            const SizedBox(height: 6),
            Text(
              desc,
              maxLines: 4,
              overflow: TextOverflow.ellipsis,
              style: TextStyle(
                fontSize: 11,
                color: isDark ? Colors.grey[400] : Colors.grey[600],
                height: 1.35,
              ),
            ),
            const SizedBox(height: 12),
            Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                Row(
                  children: [
                    Icon(
                      Icons.star,
                      size: 14,
                      color: Colors.amber[600],
                    ),
                    const SizedBox(width: 4),
                    Text(
                      saves,
                      style: const TextStyle(
                        fontSize: 10,
                        fontWeight: FontWeight.bold,
                      ),
                    ),
                  ],
                ),
                GestureDetector(
                  onTap: () {
                    Clipboard.setData(ClipboardData(text: desc));
                    ScaffoldMessenger.of(context).showSnackBar(
                      const SnackBar(
                        content: Text('Prompt copied!'),
                        behavior: SnackBarBehavior.floating,
                        duration: Duration(seconds: 1),
                      ),
                    );
                  },
                  child: Container(
                    padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 6),
                    decoration: BoxDecoration(
                      color: primaryColor,
                      borderRadius: BorderRadius.circular(8),
                    ),
                    child: const Row(
                      children: [
                        Icon(Icons.copy, size: 10, color: Colors.white),
                        SizedBox(width: 4),
                        Text(
                          'Copy',
                          style: TextStyle(
                            color: Colors.white,
                            fontSize: 10,
                            fontWeight: FontWeight.bold,
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
              ],
            ),
          ],
        ),
      ),
    );
  }
}
